### ISSUE TITLE
PDDL with empty initial state

### ISSUE THREAD

**Issue by Mengchhuong** [LAPKT-dev/LAPKT-public#49]
Hello there,

May I know is it possible for pddl domain has no initial state (empty initial state)?
or is it possible to random the initial state?

because I want to model a problem which I don't want to have initial state, I want pddl to generate plan for me from scratch, example of drawing a rectangle on a board.

anyone has knowledge on this, please kindly let me know, I hope to hear from your soon, thanks in advance.

**Comment by nirlipo** [comment]
Hi,

You need to have 1 initial state if you want to model a classical planning problem. In this case, you can have an empty initial state, but you need to make sure you have actions with no preconditions, otherwise your initial state cannot be expanded into any possible trajectory. I'd recommend continuing your PDDL questions over[ this slack](https://join.slack.com/t/theplanningcommunity/shared_invite/enQtNjg0MTIzNTE3MTY4LTQ4YTRiNjhjNmVlNmEwMGMxOTQwNTZlYWM2YTk1YjdkZmIyMTU5MzRjZjYzOWYxMjJkNGM3YTM2MWI0MmM2MGY) channel where there are several active members of the planning community giving support to different queries.
